---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - tmux
          - cmatrix
          - python3-psutil
          - zsh
          - vim

    - name: install ohmyzsh

    - name: copy wallpaper
      copy:
        src: files/wallhaven-g8gxo3.png
        dest: /usr/share/backgrounds/ansible-wallpaper.png
        owner: root
        group: root

    - name: set wallpaper
      become_user: aciidic
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

    - name: set wallpaper position
      become_user: aciidic
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    - name: copy .bashrc
      copy:
        src: files/dotfiles/bashrc
        dest: /home/aciidic/.bashrc
        owner: aciidic
        group: aciidic

    - name: copy .bash_aliases
      copy:
        src: files/dotfiles/bash_aliases
        dest: /home/aciidic/.bash_aliases
        owner: aciidic
        group: aciidic

    - name: copy .tmux.conf
      copy:
        src: files/dotfiles/tmux.conf
        dest: /home/aciidic/.tmux.conf
        owner: aciidic
        group: aciidic

    - name: copy .zshrc
      copy:
        src: files/dotfiles/zshrc
        dest: /home/aciidic/.zshrc
        owner: aciidic
        group: aciidic

    - name: add ansible user
      user:
        name: borkauto
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_borkauto
        dest: /etc/sudoers.d/borkauto
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: borkauto
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/BorkStick/ansible-desktop.git
