---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - tmux
          - cmatrix
          - python3-psutil

    - name: copy wallpaper
      copy:
        src: files/wallhaven-g8gxo3.png
        dest: /usr/share/backgrounds/ansible-wallpaper.png
        owner: root
        group: root

    - name: set wallpaper
      become_user: aciidic
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

    - name: set wallpaper position
      become_user: aciidic
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    - name: copy .bashrc
      copy:
        src: files/bashrc
        dest: /home/aciidic/.bashrc
        owner: aciidic
        group: aciidic

    - name: copy .bash_profile
      copy:
        src: files/bash_profile
        dest: /home/aciidic/.bash_aliases
        owner: aciidic
        group: aciidic
